name: 'GitHub Team Validator'
description: 'Validates team membership and repository status for namespace files'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  pr-number:
    description: 'Pull request number'
    required: true
  organization:
    description: 'GitHub organization name'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_GITHUB-TOKEN: ${{ inputs.github-token }}
    INPUT_PR-NUMBER: ${{ inputs.pr-number }}
    INPUT_ORGANIZATION: ${{ inputs.organization }}
